version: '3.7'

services:

  ontologysim_react:
    container_name: onto_fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SASS_PATH=./node_modules;./src